language: elixir
elixir:
    - 1.0.0
notifications:
  recipients:
    - eduardo@gurgel.me
otp_release:
  - 17.0
  - 17.1
env:
  - MIX_ENV=test
services:
  - riak
before_install:
  - rebar --version
script: mix test --exclude riak2
